<?php

/**
 * @file
 * General settings and methods.
 */

/**
 *
 */
define('CRM_ACCESS_DENY', FALSE);
define('CRM_ACCESS_ALLOW', TRUE);
define('CRM_ACCESS_IGNORE', NULL);

/**
 * Implements hook_permission().
 */
function crm_permission() {
  return array(
    'crm manage' => array(
      'title' => t('Manage CRM'),
    ),
    'crm administer' => array(
      'title' => t('Administer CRM'),
      'restrict access' => TRUE,
    ),
    'crm bypass access' => array(
      'title' => t('Bypass CRUD permissions'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Returns list of all available languages.
 */
function crm_language_list() {
  include_once DRUPAL_ROOT . '/includes/iso.inc';

  $languages = array();

  foreach (language_list() as $key => $language) {
    $languages[$key] = $language->name;
  }
  return $languages;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function crm_preprocess_entity(&$variables) {
  if (isset($variables['entity_type']) && strpos($variables['entity_type'], 'crm_') === 0) {
    $variables['page'] = $variables['view_mode'] == 'administrator' ? TRUE : FALSE;
  }
}
