<?php

/**
 * @file
 * General interface elements, common for all UI submodules.
 */

/**
 * Implements hook_menu().
 */
function crm_ui_menu() {
  $items = array();

  $items['admin/crm'] = array(
    'title' => 'CRM',
    'description' => 'Customer Relationship Management',
    'page callback' => 'crm_index',
    'page arguments' => array(),
    'access arguments' => array('crm manage'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/crm/config'] = array(
    'title' => 'Config',
    'description' => 'Manage CRM configuration.',
    'page callback' => 'crm_index',
    'page arguments' => array(),
    'access arguments' => array('crm administer'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 99,
  );

  return $items;
}

/**
 * Renders index based on current parent element.
 *
 * @return array
 *   Returns renderable array.
 */
function crm_index() {
  $build = array();
  $parent = menu_link_get_preferred(current_path());
  $parameters = array(
    'active_trail' => array($parent['plid']),
    'only_active_trail' => FALSE,
    'min_depth' => $parent['depth'] + 1,
    'max_depth' => $parent['depth'] + 1,
    'conditions' => array('plid' => $parent['mlid']),
  );

  $children = menu_build_tree($parent['menu_name'], $parameters);

  foreach ($children as $child) {
    $build[$child['link']['mlid']] = array(
      '#theme' => 'admin_block_content',
      '#content' => array($child['link']),
    );
  }

  return $build;
}
