<?php

/**
 * @file
 * General settings and methods.
 */

/**
 * Implements hook_permission().
 */
function micro_crm_permission() {
  return array(
    'micro crm manage' => array(
      'title' => t('Manage Micro CRM'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Returns list of all available languages.
 */
function micro_crm_language_list() {
  include_once DRUPAL_ROOT . '/includes/iso.inc';

  $languages = array();

  foreach (language_list() as $key => $language) {
    $languages[$key] = $language->name;
  }
  return $languages;
}