<?php

/**
 * @file
 * UI for contact entity.
 */

/**
 * Implements hook_menu().
 */
function micro_crm_contact_ui_menu() {
  $items = array();

  $items['admin/people/micro_crm/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'micro_crm_contact_ui_list',
    'page arguments' => array(),
    'access arguments' => array('micro crm contact overview'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/micro_crm_contact_ui.list.inc',
  );

  $items['admin/people/micro_crm/contact/%micro_crm_contact'] = array(
    'title callback' => 'micro_crm_contact_label',
    'title arguments' => array(4),
    'page callback' => 'micro_crm_contact_view',
    'page arguments' => array(4),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('view', 4),
    'type' => MENU_CALLBACK,
    'file' => 'includes/micro_crm_contact_ui.list.inc',
  );

  $items['admin/people/micro_crm/contact/%micro_crm_contact/view'] = array(
    'title' => 'View',
    'page callback' => 'micro_crm_contact_view',
    'page arguments' => array(4),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('view', 4),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/micro_crm_contact_ui.list.inc',
    'weight' => -2,
  );

  $items['admin/people/micro_crm/contact/%micro_crm_contact/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'micro_crm_contact_ui_form_wrapper',
    'page arguments' => array(4),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('update', 4),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/micro_crm_contact_ui.form.inc',
    'weight' => -1,
  );

  $items['admin/people/micro_crm/contact/%micro_crm_contact/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'micro_crm_contact_ui_form_wrapper',
    'page arguments' => array(4, TRUE),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('delete', 4),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/micro_crm_contact_ui.form.inc',
    'weight' => 99,
  );

  $items['admin/people/micro_crm/contact/add'] = array(
    'title' => 'Add contact',
    'page callback' => 'micro_crm_contact_ui_form_wrapper',
    'page arguments' => array(),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('create'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/micro_crm_contact_ui.form.inc',
  );

  $items['admin/people/micro_crm/config/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'micro_crm_index',
    'page arguments' => array(),
    'access arguments' => array('micro crm manage'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function micro_crm_contact_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'micro_crm_contact_ui') . '/includes/views',
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function micro_crm_contact_ui_entity_info_alter(&$entity_info) {

  // Uri callback.
  $entity_info['micro_crm_contact']['uri callback'] = 'micro_crm_contact_ui_uri';

  // Expose the order UI for order fields.
  $entity_info['micro_crm_contact']['bundles']['micro_crm_contact']['admin'] = array(
    'path' => 'admin/people/micro_crm/config/contact',
    'real path' => 'admin/people/micro_crm/config/contact',
    'access arguments' => array('micro crm contact administer'),
  );
}

/**
 *
 *
 * @param $contact
 */
function micro_crm_contact_ui_uri($contact) {
//  // First look for a return value in the default entity uri callback.
//  $uri = commerce_order_uri($order);
//
//  // If a value was found, return it now.
//  if (!empty($uri)) {
//    return $uri;
//  }

  // Only return a value if the user has permission to view the order.
  if (micro_crm_contact_access('view', $contact)) {
    return array(
      'path' => 'admin/people/micro_crm/contact/' . entity_id('micro_crm_contact', $contact),
    );
  }

  return NULL;
}
