<?php

/**
 * @file
 * UI for contact entity.
 */

/**
 * Implements hook_menu().
 */
function micro_crm_contact_ui_menu() {
  $items = array();

  $items['admin/people/micro_crm/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'micro_crm_contact_ui_list',
    'page arguments' => array(),
    'access arguments' => array('micro crm contact overview'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/micro_crm_contact_ui.list.inc',
  );

  $items['admin/people/micro_crm/contact/%micro_crm_contact'] = array(
    'title callback' => 'micro_crm_contact_label',
    'title arguments' => array(4),
    'page callback' => 'micro_crm_contact_ui_form_wrapper',
    'page arguments' => array(4),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('edit', 4),
    'type' => MENU_CALLBACK,
    'file' => 'includes/micro_crm_contact_ui.form.inc',
  );

  $items['admin/people/micro_crm/contact/add'] = array(
    'title' => 'Add contact',
    'page callback' => 'micro_crm_contact_ui_form_wrapper',
    'page arguments' => array(),
    'access callback' => 'micro_crm_contact_access',
    'access arguments' => array('create'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/micro_crm_contact_ui.form.inc',
  );

  $items['admin/people/micro_crm/config/contact'] = array(
    'title' => 'Contact',
    'page callback' => 'micro_crm_index',
    'page arguments' => array(),
    'access arguments' => array('micro crm manage'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function micro_crm_contact_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'micro_crm_contact_ui') . '/includes/views',
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function micro_crm_contact_ui_entity_info_alter(&$entity_info) {

  // Expose the order UI for order fields.
  $entity_info['micro_crm_contact']['bundles']['micro_crm_contact']['admin'] = array(
    'path' => 'admin/people/micro_crm/config/contact',
    'real path' => 'admin/people/micro_crm/config/contact',
    'access arguments' => array('micro crm contact administer'),
  );
}

