<?php

/**
 * @file
 *
 */

/**
 * Implements hook_entity_info_alter().
 */
function crm_email_message_entity_info_alter(&$entity_info) {
  $bundle = array(
    'label' => t('E-mail'),
    'module' => 'crm_email_message',
  );
  $entity_info['crm_message']['bundles']['email'] = $bundle;
}

/**
 * Implements hook_mail().
 */
function crm_email_message_mail($key, &$message, $params) {

  switch ($key) {
    case 'message':
      $message['subject'] = $params['subject'];
      $formatted_text = $params['body'];
      $message['body'] = check_markup($formatted_text['value'], $formatted_text['format']);
      break;
  }

}
