<?php

/**
 * @file
 *
 */

define('CRM_MESSAGE_STATUS_DRAFT', 'draft');
define('CRM_MESSAGE_STATUS_QUEUED', 'queued');
define('CRM_MESSAGE_STATUS_SENT', 'sent');

module_load_include('inc', 'crm_message', 'crm_message.entity');

/**
 * Implements hook_views_api().
 */
function crm_message_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'crm_message') . '/includes/views',
  );
}

/**
 * Implements hook_hook_info().
 */
function crm_message_hook_info() {
  $hooks = array(
    'crm_message_status_info' => array(
      'group' => 'crm',
    ),
    'crm_message_status_info_alter' => array(
      'group' => 'crm',
    ),
    'crm_message_uri' => array(
      'group' => 'crm',
    ),
    'crm_message_view' => array(
      'group' => 'crm',
    ),
    'crm_message_presave' => array(
      'group' => 'crm',
    ),
    'crm_message_update' => array(
      'group' => 'crm',
    ),
    'crm_message_insert' => array(
      'group' => 'crm',
    ),
    'crm_message_delete' => array(
      'group' => 'crm',
    ),
    'crm_message_send' => array(
      'group' => 'crm',
    ),
  );
  return $hooks;
}

/**
 * Implements hook_cron_queue_info().
 */
function crm_message_cron_queue_info() {
  $queues['crm_message_queue_postponed'] = array(
    'worker callback' => 'crm_message_postpone_worker',
    'time' => '10',
  );
  $queues['crm_message_queue'] = array(
    'worker callback' => 'crm_message_send_worker',
    'time' => '300',
  );
  return $queues;
}

/**
 * Implements hook_permission().
 */
function crm_message_permission() {
  return array(
    'crm message overview' => array(
      'title' => t('Access to message list'),
    ),
    'crm message create' => array(
      'title' => t('Create new message'),
    ),
    'crm message view' => array(
      'title' => t('View message'),
    ),
    'crm message update' => array(
      'title' => t('Update message'),
    ),
    'crm message delete' => array(
      'title' => t('Delete message'),
    ),
    'crm message send' => array(
      'title' => t('Send message'),
    ),
  );
}

/**
 * Implements hook_crm_channel_fields_info().
 */
function crm_message_crm_channel_fields_info() {
  $types = crm_channel_types(TRUE);
  $array = array();
  foreach ($types as $key => $bundle) {
    $array['instances'][$key . '_crm_channel_single'] = array(
      'label' => t('Recipient (Channel)'),
      'widget' => array(
        'weight' => -99,
        'type' => 'entityreference_autocomplete',
        'module' => 'entityreference',
        'active' => 1,
        'settings' => array(
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'path' => '',
        ),
      ),
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'display' => array(
        'default' => array(
          'label' => 'above',
          'type' => 'entityreference_label',
          'settings' => array(
            'link' => FALSE,
          ),
          'module' => 'entityreference',
          'weight' => -99,
        ),
      ),
      'required' => 1,
      'description' => t('Recipient has to be registered and valid channel.'),
      'default_value' => NULL,
      'field_name' => 'crm_channel_single',
      'entity_type' => 'crm_message',
      'bundle' => $key,
      'deleted' => 0,
    );
  }
  drupal_alter('crm_message_crm_channel_fields_info', $array);
  return $array;
}

/**
 * Implements hook_crm_message_update().
 */
function crm_message_crm_message_update($message) {
  if (isset($message->original->status) && $message->original->status == CRM_MESSAGE_STATUS_DRAFT && $message->status == CRM_MESSAGE_STATUS_SENT) {
    watchdog('crm_message', 'Message (message_id: @message) has been sent', array('@message' => $message->message_id), WATCHDOG_NOTICE, l('view', 'admin/crm/message/' . $message->message_id));
  }
  else {
    watchdog('crm_message', 'Message (message_id: @message) has been saved', array('@message' => $message->message_id), WATCHDOG_NOTICE, l('view', 'admin/crm/message/' . $message->message_id));
  }
}

/**
 * Implements hook_crm_message_status_info().
 */
function crm_message_crm_message_status_info() {
  $status = array();

  $status[CRM_MESSAGE_STATUS_DRAFT] = array(
    'title' => t('Draft'),
    'description' => t('Draft message'),
    'weight' => -99,
  );

  $status[CRM_MESSAGE_STATUS_QUEUED] = array(
    'title' => t('Queued'),
    'description' => t('Message has been queued and will be sent soon.'),
    'weight' => 0,
  );

  $status[CRM_MESSAGE_STATUS_SENT] = array(
    'title' => t('Sent'),
    'description' => t('Message has been sent'),
    'weight' => 99,
  );

  return $status;
}

/**
 * Returns all statuses message declared by modules.
 *
 * @return array
 *   List of statuses
 */
function crm_message_statuses() {
  // First check the static cache for an order states array.
  $statuses = &drupal_static(__FUNCTION__);

  // If it did not exist, fetch the statuses now.
  if (empty($statuses)) {
    $statuses = module_invoke_all('crm_message_status_info');

    // Give other modules a chance to alter the order states.
    drupal_alter('crm_message_status_info', $statuses);

    uasort($statuses, 'drupal_sort_weight');
  }

  return $statuses;
}

/**
 * @param $status
 * @return null
 */
function crm_message_status_get_name($status) {
  $statuses = crm_message_statuses();
  if (isset($statuses[$status]['title'])) {
    return $statuses[$status]['title'];
  }
  return NULL;
}

/**
 * Returns list of available statuses.
 */
function crm_message_status_options_list() {

  $options = array();

  foreach (crm_message_statuses() as $key => $status) {
    $options[$key] = $status['title'];
  }

  return $options;
}

/**
 * @param $message
 */
function crm_message_send($message) {
  if (!isset($message->type)) {
    watchdog('crm_message', 'Message (message_id: @message_id) has incorrect type.', array('@message_id' => $message->message_id), WATCHDOG_ERROR);
    return FALSE;
  }
  $type = $message->type;
  $entity = entity_get_info('crm_message');
  if (!isset($type) || !isset($entity['bundles'][$type]['module'])) {
    return FALSE;
  }
  $module = $entity['bundles'][$type]['module'];
  if ($value = module_invoke($module, 'crm_message_send', $message)) {
    if ($value == TRUE) {
      $message->status = CRM_MESSAGE_STATUS_SENT;
      $message->revision = TRUE;
      $message->log = format_string('Message (message_id: @message_id) has been sent', array('@message_id' => $message->message_id));
      entity_save('crm_message', $message);
      watchdog('crm_message', 'Message (message_id: @message_id) has been sent', array('@message_id' => $message->message_id), WATCHDOG_NOTICE);
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Returns boolean value if channel is supported by message module or not.
 *
 * @param $type
 * @return bool
 */
function _crm_message_channel_supported($type) {
  $entity = entity_get_info('crm_message');
  if (isset($entity['bundles'][$type])) {
    return TRUE;
  }
  else {
    return FALSE;
  }
}

/**
 * Returns list of types (bundles) in key => title format.
 *
 * @return array
 */
function crm_message_types() {
  // First check the static cache for a product types array.
  $message_types = &drupal_static(__FUNCTION__);

  // If it did not exist, fetch the types now.
  if (!isset($message_types)) {
    $message_types = array();

    $entity = entity_get_info('crm_message');
    if (isset($entity['bundles'])) {
      foreach ($entity['bundles'] as $key => $bundle) {
        // @todo: add something here or simplify it.
        $message_types[$key] = $bundle['label'];
      }
    }
  }

  return $message_types;
}

/**
 * Returns type label.
 */
function crm_message_type_get_name($type) {
  $types = crm_message_types();
  if (isset($types[$type])) {
    return $types[$type];
  }
  return NULL;
}

/**
 * @param $values
 * @param string $entity_type
 */
function crm_message_create($values, $entity_type = 'crm_message') {
  if (isset($values['channel']) && isset($values['channel']->type)) {
    $bundle = $values['channel']->type;
  }
  elseif ($values['type']) {
    $bundle = $values['type'];
  }
  else {
    return FALSE;
  }
  $entity = entity_get_info($entity_type);
  if (!isset($entity['bundles'][$bundle]['module'])) {
    return FALSE;
  }
  $module = $entity['bundles'][$bundle]['module'];
  if (!function_exists($module . '_crm_message_create')) {
    return FALSE;
  }
  return module_invoke($module, 'crm_message_create', $values, $entity_type);
}

/**
 *
 *
 * It takes only queued messages!
 *
 * @param $field
 */
function crm_message_queue_populate($conditions = NULL) {
  $queue = DrupalQueue::get('crm_message_queue');
  $queue->createQueue();

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'crm_message')
    ->propertyCondition('status', CRM_MESSAGE_STATUS_QUEUED)
    ->propertyOrderBy('updated', 'ASC');

  foreach ($conditions as $condition) {
    if ($condition['type'] == 'property') {
      $query->propertyCondition($condition['column'], $condition['value']);
    }
    elseif ($condition['type'] == 'entity') {
      $query->entityCondition($condition['name'], $condition['value']);
    }
    elseif ($condition['type'] == 'field') {
      $query->fieldCondition($condition['field'], $condition['column'], $condition['value']);
    }
  }

  $result = $query->execute();

  if (isset($result['crm_message'])) {
    foreach(array_keys($result['crm_message']) as $key) {
      $queue->createItem($key);
    }
  }

}

/**
 * @param $message_id
 * @return bool
 */
function crm_message_send_worker($message_id) {
  $message = entity_load_single('crm_message', $message_id);
  if (!$message || !is_object($message)) {
    watchdog('crm_message', 'Message (message_id: @message_id) looks incorrect. Worker will not try to send it anymore. Debug: @message', array('@message_id' => $message_id, '@message' => print_r($message, TRUE)), WATCHDOG_ALERT);
    return -1;
  }
  try {
    $result = crm_message_send_worker_iteration($message);
  }
  catch (Exception $e) {
    crm_message_send_worker_iteration_requeue($message, $e->getMessage());
    return FALSE;
  }
  if (!$result) {
    crm_message_send_worker_iteration_requeue($message);
    return FALSE;
  }
  return $result;
}

/**
 * @param $message_id
 * @param $context
 */
function crm_message_send_worker_batch_wrapper($message_id, &$context) {
  $result = crm_message_send_worker($message_id);
  if ($result === -1) {
    // Error, skip.
  }
  elseif ($result) {
    // Sent.
    $context['results']['iterations'][] = array(
      'message_id' => $message_id,
      'status' => CRM_MESSAGE_STATUS_SENT,
    );
  }
  else {
    // Re-queued.
    $context['results']['iterations'][] = array(
      'message_id' => $message_id,
      'status' => CRM_MESSAGE_STATUS_QUEUED,
    );
  }
}

/**
 * @param $message
 * @return bool
 */
function crm_message_send_worker_iteration($message) {
  if ($message->status <> CRM_MESSAGE_STATUS_QUEUED) {
    return TRUE;
  }
  return crm_message_send($message);
}

/**
 * @param $message
 * @param null $error_message
 */
function crm_message_send_worker_iteration_requeue($message, $error_message = NULL) {
  $queue = DrupalQueue::get('crm_message_queue_postponed');
  $queue->createQueue();
  // In case Drupal couldn't send message - re-queue it.
  if ($error_message) {
    watchdog('crm_message', 'Unable to send message (message_id: @message_id). Error: @error_message', array('@message_id' => $message->message_id, '@error_message' => $error_message), WATCHDOG_ALERT);
  }
  else {
    watchdog('crm_message', 'Unable to send message (message_id: @message_id)', array('@message_id' => $message->message_id), WATCHDOG_ALERT);
  }
  $queue->createItem($message->message_id);
}

/**
 * @param $message_id
 */
function crm_message_postpone_worker($message_id) {
  $queue = DrupalQueue::get('crm_message_queue');
  $queue->createQueue();
  $queue->createItem($message_id);
}
