<?php

/**
 * @file
 */

define('CRM_CAMPAIGN_STATUS_REGISTERED', 'registered');
define('CRM_CAMPAIGN_STATUS_QUEUED', 'queued');
define('CRM_CAMPAIGN_STATUS_SENT', 'sent');

module_load_include('inc', 'crm_campaign', 'crm_campaign.entity');

/**
 * Implements hook_menu().
 */
function crm_campaign_menu() {
  $items = array();

  $items['admin/crm/campaign/%crm_campaign'] = array(
    'title callback' => 'crm_campaign_label',
    'title arguments' => array(3),
    'page callback' => 'crm_campaign_view',
    'page arguments' => array(3, 'administrator', NULL, TRUE),
    'access callback' => 'crm_campaign_access',
    'access arguments' => array('view', 3),
    'type' => MENU_CALLBACK,
  );

  $items['admin/crm/config/campaign'] = array(
    'title' => 'Campaign',
    'description' => 'Manage Campaign configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('crm_campaign_settings'),
    'access arguments' => array('crm administer'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'crm_campaign.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_hook_info().
 */
function crm_campaign_hook_info() {
  $info['crm_campaign_method_info'] = array(
    'group' => 'crm',
  );
  $info['crm_campaign_status_info'] = array(
    'group' => 'crm',
  );
  return $info;
}

/**
 * Implements hook_permission().
 */
function crm_campaign_permission() {
  return array(
    'crm campaign overview' => array(
      'title' => t('Access to campaign list'),
    ),
    'crm campaign create' => array(
      'title' => t('Create new campaign'),
    ),
    'crm campaign view' => array(
      'title' => t('View campaign'),
    ),
    'crm campaign update' => array(
      'title' => t('Update campaign'),
    ),
    'crm campaign delete' => array(
      'title' => t('Delete campaign'),
    ),
    'crm campaign send' => array(
      'title' => t('Send campaign'),
    ),
  );
}

/**
 * Implements hook_crm_channel_fields_info().
 *
 * @todo: move to crm.inc
 */
function crm_campaign_crm_channel_fields_info() {
  $types = crm_channel_types(TRUE);
  $array = array();
  foreach ($types as $key => $bundle) {
    $array['instances'][$key . '_crm_campaign_single'] = array(
      'label' => t('Campaign'),
      'widget' => array(
        'weight' => '5',
        'type' => 'entityreference_autocomplete',
        'module' => 'entityreference',
        'active' => 1,
        'settings' => array(
          'match_operator' => 'CONTAINS',
          'size' => '60',
          'path' => '',
        ),
      ),
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'display' => array(
        'default' => array(
          'label' => 'inline',
          'type' => 'entityreference_label',
          'weight' => 98,
          'settings' => array(
            'link' => 1,
          ),
          'module' => 'entityreference',
        ),
      ),
      'required' => 0,
      'description' => '',
      'default_value' => NULL,
      'field_name' => 'crm_campaign_single',
      'entity_type' => 'crm_message',
      'bundle' => $key,
      'deleted' => 0,
    );
  }
  drupal_alter('crm_campaign_crm_channel_fields_info', $array);
  return $array;
}

/**
 * Implements hook_cron().
 */
function crm_campaign_cron() {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'crm_campaign')
    ->propertyCondition('status', CRM_CAMPAIGN_STATUS_QUEUED, '=');

  $result = $query->execute();

  if (isset($result['crm_campaign'])) {
    foreach ($result['crm_campaign'] as $campaign_id => $campaign) {
      if (_crm_campaign_is_sent($campaign_id)) {
        try {
          $campaign = entity_load_single('crm_campaign', $campaign_id);
          $campaign->status = CRM_CAMPAIGN_STATUS_SENT;
          $campaign->log = 'Campaign has been sent';
          $campaign->revision = TRUE;
          entity_save('crm_campaign', $campaign);
        }
        catch (Exception $e) {
          watchdog_exception('crm_campaign', $e);
        }
      }
    }
  }
}

/**
 * Implements hook_action_info().
 */
function crm_campaign_action_info() {
  $info['crm_campaign_channel_send_message'] = array(
    'type' => 'crm_channel',
    'label' => t('Send campaign'),
    'configurable' => TRUE,
    'permissions' => array('crm campaign create', 'crm campaign send'),
    'aggregate' => TRUE,
    'behavior' => array('null'),
  );

  $info['crm_campaign_contact_send_message'] = array(
    'type' => 'crm_contact',
    'label' => t('Send campaign'),
    'configurable' => TRUE,
    'permissions' => array('crm campaign create', 'crm campaign send'),
    'aggregate' => TRUE,
    'behavior' => array('null'),
  );

  $info['crm_campaign_user_send_message'] = array(
    'type' => 'user',
    'label' => t('Send campaign'),
    'configurable' => TRUE,
    'permissions' => array('crm campaign create', 'crm campaign send'),
    'aggregate' => TRUE,
    'behavior' => array('null'),
  );

  return $info;
}

/**
 * @return array
 */
function crm_campaign_method_info($method = NULL) {
  // First check the static cache for an array.
  $methods = &drupal_static(__FUNCTION__);

  // If it did not exist, fetch it now.
  if (empty($methods)) {
    $methods = module_invoke_all('crm_campaign_method_info');

    // Give other modules a chance to alter the array.
    drupal_alter('crm_campaign_method_info', $methods);
  }

  if (isset($method)) {
    return isset($methods[$method]) ? $methods[$method] : NULL;
  }

  return $methods;
}

/**
 * Implements hook_views_api().
 */
function crm_campaign_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'crm_campaign') . '/includes/views',
  );
}

/**
 * Implements hook_crm_campaign_status_info().
 */
function crm_campaign_crm_campaign_status_info() {
  $status = array();

  $status[CRM_CAMPAIGN_STATUS_REGISTERED] = array(
    'title' => t('Registered'),
    'description' => t('Registered, unprocessed campaign'),
    'weight' => -99,
  );

  $status[CRM_CAMPAIGN_STATUS_QUEUED] = array(
    'title' => t('Queued'),
    'description' => t('Campaign queued to send.'),
    'weight' => 0,
  );

  $status[CRM_CAMPAIGN_STATUS_SENT] = array(
    'title' => t('Sent'),
    'description' => t('Fully sent campaign.'),
    'weight' => 99,
  );

  return $status;
}

/**
 * Returns all statuses campaign declared by modules.
 *
 * @return array
 *   List of statuses
 */
function crm_campaign_statuses() {
  // First check the static cache for an order states array.
  $statuses = &drupal_static(__FUNCTION__);

  // If it did not exist, fetch the statuses now.
  if (empty($statuses)) {
    $statuses = module_invoke_all('crm_campaign_status_info');

    // Give other modules a chance to alter the order states.
    drupal_alter('crm_campaign_status_info', $statuses);

    uasort($statuses, 'drupal_sort_weight');
  }

  return $statuses;
}

/**
 * Returns status label.
 *
 * @param $status
 * @return null
 */
function crm_campaign_status_get_name($status) {
  $statuses = crm_campaign_statuses();
  if (isset($statuses[$status]['title'])) {
    return $statuses[$status]['title'];
  }
  return NULL;
}

/**
 * Returns list of available statuses.
 */
function crm_campaign_status_options_list() {

  $options = array();

  foreach (crm_campaign_statuses() as $key => $status) {
    $options[$key] = $status['title'];
  }

  return $options;
}

/**
 * Returns list of all campaigns.
 *
 * @param null $status
 *   Campaign status.
 *
 * @return null|array
 *   List of campaign objects or NULL if nothing found.
 */
function crm_campaign_campaigns($status = NULL) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'crm_campaign');
  if ($status) {
    $query->propertyCondition('status', $status);
  }
  $query->propertyOrderBy('title', 'ASC')
    ->addTag('crm_campaign_campaigns')
    ->addMetaData('status', $status);

  $result = $query->execute();
  if (!isset($result['crm_campaign'])) {
    return NULL;
  }
  return entity_load('crm_campaign', array_keys($result['crm_campaign']));
}

/**
 * Returns list of campaigns in a option list format (key => value pairs).
 *
 * @param string $status
 *   Campaign status.
 *
 * @todo There is no need to load objects. Do simple query to load only titles
 * and ids.
 */
function crm_campaign_option_list($status = NULL) {
  $array = array();
  if (!($campaigns = crm_campaign_campaigns($status))) {
    return $array;
  }
  foreach ($campaigns as $campaign) {
    $array[$campaign->campaign_id] = $campaign->title;
  }
  return $array;
}

/**
 * Implements hook_form_alter().
 */
function crm_campaign_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['crm_campaign_single']) && isset($form['#entity_type']) && $form['#entity_type'] == 'crm_message') {
    // Hide all occurrences of crm_campaign_single field.
    $form['crm_campaign_single']['#access'] = FALSE;
  }
}

/**
 * Manipulates object by populating crm_channel field value.
 *
 * @param $campaign
 *   Campaign entity. Passed by reference.
 */
function _crm_campaign_method_prepopulate(&$campaign) {
  if (!isset($campaign->data['manage_recipients']['methods'])) {
    return;
  }
  if (empty($campaign->data['manage_recipients']['methods'])) {
    return;
  }
  if (!is_array($campaign->data['manage_recipients']['methods'])) {
    return;
  }
  if (isset($campaign->data['manage_recipients']['rebuild']) && !$campaign->data['manage_recipients']['rebuild']) {
    return;
  }
  if (isset($campaign->data['manage_recipients']['rebuild']) && $campaign->data['manage_recipients']['rebuild'] && isset($campaign->data['manage_recipients']['remove']) && $campaign->data['manage_recipients']['remove']) {
    try {
      $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
      $wrapper->crm_channel->set(NULL);
    }
    catch (Exception $e) {
      watchdog_exception('crm_campaign', $e);
      return;
    }
  }
  $methods = crm_campaign_method_info();
  uasort($campaign->data['manage_recipients']['methods'], 'drupal_sort_weight');
  foreach ($campaign->data['manage_recipients']['methods'] as $method => $options) {
    if (!isset($methods[$method]['auto']) || !isset($methods[$method]['method callback']) || !isset($methods[$method]['method defaults']) || !$methods[$method]['auto']) {
      continue;
    }
    if (function_exists($methods[$method]['method callback'])) {
      $options += $methods[$method]['method defaults'];
      $methods[$method]['method callback']($campaign, $options);
    }
  }
}

/**
 * Gets form implementation based on 'method form' property or forms namespace.
 *
 * If form does not exist or is not needed at all return dummy empty array.
 *
 * @param $method
 *   Method key.
 * @param array $options
 *   Arrays with custom options. Default values will be added here.
 *
 * @return array
 *   Form array. At least dummy element of type 'value' to preserve data
 *   structure.
 */
function crm_campaign_method_get_form($method, $options = array()) {
  $method_key = $method;
  $method = crm_campaign_method_info($method);
  if (isset($method['method defaults'])) {
    $options += $method['method defaults'];
  }
  if (isset($method['method form']) && function_exists($method['method form'])) {
   $form = $method['method form']($options);
  }
  elseif ($form = module_invoke_all('crm_campaign_method_' . $method_key . '_form', $options)) {
    // If form is not empty skip else.
  }
  else {
    $form = array(
      '#type' => 'value',
      '#value' => array(),
    );
    return $form;
  }
  return array(
    '#type' => 'fieldset',
    '#title' => $method['name'],
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  ) + $form;
}

/**
 * Returns boolean value which indicates if channel is on the campaign recipient
 * list or not.
 *
 * @param $campaign
 *   Campaign object.
 * @param $channel_id
 *   Channel ID.
 *
 * @return bool
 *   TRUE or FALSE.
 */
function crm_campaign_channel_exists($campaign, $channel_id) {
  try {
    $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
    return in_array($channel_id, $wrapper->crm_channel->raw());
  }
  catch (Exception $e) {
    watchdog_exception('crm_campaign', $e);
    return FALSE;
  }
}

/**
 * Compares lists and adds missing channels to campaign's crm_channel field.
 *
 * @param $campaign
 *   Campaign object passed by reference.
 * @param object|array $channel
 *   Array of channels or single object.
 *
 * @deprecated
 *   Use crm_campaign_add_channel instead.
 */
function crm_campaign_add_channel_to_campaign(&$campaign, $channel) {
  $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
  $values = $wrapper->crm_channel->raw();
  if (is_object($channel)) {
    $channel = array($channel->channel_id => $channel);
  }
  $keys = array_keys($channel);
  $diff = array_diff($keys, $values);
  $values = array_merge($values, $diff);
  asort($values);
  $wrapper->crm_channel->set($values);
}

/**
 * Compares and removes channels from campaign.
 *
 * @param $campaign
 *   Campaign object passed by reference.
 * @param object| array $channel
 *   Array of channels or single object.
 *
 * @deprecated
 *   Use crm_campaign_remove_channel instead.
 */
function crm_campaign_remove_channel_from_campaign(&$campaign, $channel) {
  $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
  $values = $wrapper->crm_channel->raw();
  if (is_object($channel)) {
    $channel = array($channel->channel_id => $channel);
  }
  $keys = array_keys($channel);
  $values = array_diff($values, $keys);
  asort($values);
  $wrapper->crm_channel->set($values);
}

/**
 * Adds channel to campaign entity.
 *
 * @param $campaign
 * @param $channel
 * @return bool
 *
 * @todo: Use syntax from crm_campaign_add_channel_to_campaign
 */
function crm_campaign_add_channel(&$campaign, $channel) {
  if (crm_campaign_channel_exists($campaign, $channel->channel_id)) {
    return TRUE;
  }
  try {
    $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
    $wrapper->crm_channel[] = $channel;
    return TRUE;
  }
  catch (Exception $e) {
    watchdog_exception('crm_campaign', $e);
    return FALSE;
  }
}

/**
 * Removes channel from campaign entity.
 *
 * @param $campaign
 * @param $channel_id
 * @return bool
 *
 * @todo: Use syntax from crm_campaign_remove_channel_from_campaign
 */
function crm_campaign_remove_channel(&$campaign, $channel_id) {
  if (!crm_campaign_channel_exists($campaign, $channel_id)) {
    return TRUE;
  }
  try {
    $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
    $key = array_search($channel_id, $campaign->crm_channel->raw());
    unset($wrapper->crm_channel[$key]);
    return TRUE;
  }
  catch (Exception $e) {
    watchdog_exception('crm_campaign', $e);
    return FALSE;
  }
}

/**
 * @param $campaign_id
 * @return bool
 */
function _crm_campaign_is_sent($campaign_id) {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'crm_message')
    ->propertyCondition('status', CRM_CAMPAIGN_STATUS_SENT, '<>')
    ->fieldCondition('crm_campaign_single', 'target_id', $campaign_id, '=');

  $result = $query->execute();
  if (!isset($result['crm_message']) || !count($result['crm_message'])) {
    return TRUE;
  }
  return FALSE;
}

/**
 * @param $campaign
 * @param $channel
 * @return bool|mixed
 */
function _crm_campaign_message_exists($campaign, $channel) {
  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'crm_message')
    ->fieldCondition('crm_campaign_single', 'target_id', $campaign->campaign_id, '=')
    ->fieldCondition('crm_channel_single', 'target_id', $channel->channel_id, '=')
    ->range(0, 1);

  $result = $query->execute();

  if (isset($result['crm_message'])) {
    $ids = array_keys($result['crm_message']);
    return entity_load_single('crm_message', reset($ids));
  }
  return FALSE;
}

/**
 *
 *
 * @param $campaign
 * @param $channel
 * @param bool $send
 *
 * @return bool|mixed
 */
function crm_campaign_channel_create_message($campaign, $channel) {
  $type = $channel->type;
  $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
  $templates = $wrapper->crm_message_template->raw();

  if (!is_array($templates) && is_numeric($templates)) {
    if ($wrapper->crm_message_template->getBundle() == $type) {
      $template = $wrapper->crm_message_template->value();
    }
  }
  elseif (is_array($templates)) {
    foreach ($wrapper->crm_message_template as $template_wrapper) {
      if ($template_wrapper->getBundle() == $type) {
        $template = $template_wrapper->value();
        break;
      }
    }
  }
  if (!isset($template)) {
    return FALSE;
  }

  // Create message based on template.
  $message = crm_message_template_apply($template, $channel, array(), FALSE);
  $message->status = CRM_MESSAGE_STATUS_QUEUED;
  $message->revision = TRUE;
  $message->log = t('Message has been queued.');
  $message_wrapper = entity_metadata_wrapper('crm_message', $message);
  $message_wrapper->crm_campaign_single->set($campaign);
  $message_wrapper->save();

  // Return message.
  return $message;
}

/**
 * Send campaign action: form callback.
 */
function crm_campaign_action_send_message_form($context, &$form_state) {
  $form['message_type'] = array(
    '#type' => 'select',
    '#title' => t('Choose message type'),
    '#required' => TRUE,
    '#options' => crm_message_template_types(),
    '#ajax' => array(
      'wrapper' => 'crm_campaign_message_template',
      'callback' => 'crm_campaign_action_send_message_form_ajax_callback',
    ),
  );

  $form['message'] = array(
    '#type' => 'container',
    '#attributes' => array(
      'id' => 'crm_campaign_message_template',
    ),
  );
  if (isset($form_state['values']['message_type'])) {

    $form['message']['title'] = array(
      '#type' => 'textfield',
      '#title' => t('Title'),
      '#required' => TRUE,
      '#description' => t("This value won't be exposed to end user."),
    );

    $form['message']['machine_name'] = array(
      '#type' => 'machine_name',
      '#machine_name' => array(
        'exists' => 'crm_message_template_exists_by_name',
        'source' => array('message', 'title'),
      ),
    );

    $template = entity_create('crm_message_template', array('type' => $form_state['values']['message_type']));

    $form['message']['template'] = array(
      '#type' => 'value',
      '#value' => $template,
    );

    field_attach_form('crm_message_template', $template, $form['message'], $form_state);
  }

  return $form;
}

/**
 * Send message to channel: action form ajax callback.
 *
 * Inject message template form.
 */
function crm_campaign_action_send_message_form_ajax_callback($form, &$form_state) {
  return $form['message'];
}

/**
 * Send campaign action: form submit handler.
 */
function crm_campaign_action_send_message_form_submit($form, &$form_state) {
  $transaction = db_transaction();
  try {
    $campaign = entity_create('crm_campaign', array(
      'title' => $form_state['values']['title'],
      'status' => CRM_CAMPAIGN_STATUS_REGISTERED,
      'log' => t('Campaign created from Action (VBO)'),
    ));
    $campaign_wrapper = entity_metadata_wrapper('crm_campaign', $campaign);

    $template = $form_state['values']['template'];
    $template->name = $form_state['values']['machine_name'];
    field_attach_submit('crm_message_template', $template, $form['message'], $form_state);
    $template->log = t('Message template created by crm_campaign (VBO)');
    entity_save('crm_message_template', $template);

    $campaign_wrapper->crm_message_template->set(array($template));
    $campaign_wrapper->save();
  }
  catch (Exception $e) {
    $transaction->rollback();
    throw $e;
  }

  return array('crm_campaign' => $campaign, 'type' => $template->type);
}

/**
 * Campaign actions: send single message helper.
 *
 * @param $channel
 *   Channel object.
 * @param $context
 *   Context array - passed by reference.
 *
 * @return bool
 */
function _crm_campaign_message_send($channel, &$context) {
  try {
    // Add channel to campaign.
    crm_campaign_add_channel($context['crm_campaign'], $channel);
    $context['crm_campaign']->revision = FALSE;
    entity_save('crm_campaign', $context['crm_campaign']);

    // Generate message for channel.
    $message = crm_campaign_channel_create_message($context['crm_campaign'], $channel);

    // Send message.
    crm_message_send($message);
    return TRUE;
  }
  catch (Exception $e) {
    watchdog_exception('crm_campaign', $e);
    return FALSE;
  }
}

/**
 * Send message to channel: action callback.
 *
 * @param $channels
 * @param array $context
 */
function crm_campaign_channel_send_message($channels, &$context = array()) {

  $campaign = entity_load_single('crm_campaign', $context['crm_campaign']->campaign_id);

  // If array of channels.
  if (is_array($channels)) {
    crm_campaign_add_channel_to_campaign($campaign, $channels);
    $campaign->status = CRM_CAMPAIGN_STATUS_REGISTERED;
  }
  $campaign->log = 'Updated list of channels.';
  entity_save('crm_campaign', $campaign);

  if (module_exists('crm_campaign_ui')) {
    $uri = entity_uri('crm_campaign', $campaign);
    drupal_goto($uri['path'] . '/send');
    return TRUE;
  }
  else {
    $batch_operations = array();
    $wrapper = entity_metadata_wrapper('crm_campaign', $campaign);
    $channels = $wrapper->crm_channel->value();
    foreach ($channels as $channel) {
      $batch_operations[] = array(
        'crm_campaign_batch_prepare_item',
        array(
          $campaign,
          $channel,
        ),
      );
    }
    $batch = array(
      'operations' => $batch_operations,
      'finished' => 'crm_campaign_batch_send_finished',
    );
    batch_set($batch);
    return TRUE;
  }
}

/**
 * Send message to channel: action form callback.
 */
function crm_campaign_channel_send_message_form($context, &$form_state) {
  return crm_campaign_action_send_message_form($context, $form_state);
}

/**
 * Send message to channel: action form submit handler.
 */
function crm_campaign_channel_send_message_submit($form, &$form_state) {
  return crm_campaign_action_send_message_form_submit($form, $form_state);
}

/**
 * Send message to channel: action callback.
 *
 * @param $contacts
 * @param array $context
 */
function crm_campaign_contact_send_message($contacts, &$context = array()) {

  $channels = array();
  foreach ($contacts as $contact) {
    if ($channel = crm_contact_channel_get_default($contact, $context['type'])) {
      $channels[$channel->channel_id] = $channel;
    }
  }

  // We are gonna send message to only default channel for contact.
  return crm_campaign_channel_send_message($channels, $context);
}

/**
 * Send message to contact: action form callback.
 */
function crm_campaign_contact_send_message_form($context, &$form_state) {
  return crm_campaign_action_send_message_form($context, $form_state);
}

/**
 * Send message to contact: action form submit handler.
 */
function crm_campaign_contact_send_message_submit($form, &$form_state) {
  return crm_campaign_action_send_message_form_submit($form, $form_state);
}

/**
 * Send message to channel: action callback.
 *
 * @param $contact
 * @param array $context
 */
function crm_campaign_user_send_message($users, &$context = array()) {

  $contacts = array();
  foreach ($users as $user) {
    if ($contact = crm_user_load_contact($user->uid)) {
      $contacts[$contact->contact_id] = $contact;
    }
  }

  // We are gonna send message to only default channel for contact.
  return crm_campaign_contact_send_message($contacts, $context);
}

/**
 * Send message to contact: action form callback.
 */
function crm_campaign_user_send_message_form($context, &$form_state) {
  return crm_campaign_action_send_message_form($context, $form_state);
}

/**
 * Send message to contact: action form submit handler.
 */
function crm_campaign_user_send_message_submit($form, &$form_state) {
  return crm_campaign_action_send_message_form_submit($form, $form_state);
}

/**
 * @param $campaign
 * @param $channel
 * @param $context
 */
function crm_campaign_batch_prepare_item($campaign, $channel, &$context) {
  $context['results']['campaign'] = $campaign->campaign_id;
  $queue_mode = variable_get('crm_campaign_queue', FALSE);

  if ($queue_mode) {
    $queue = DrupalQueue::get('crm_message_queue');
    $queue->createQueue();
  }

  $message = _crm_campaign_message_exists($campaign, $channel);
  if (is_object($message) && $message->status == CRM_MESSAGE_STATUS_SENT) {
    return;
  }

  if (is_object($message) && $message->status <> CRM_MESSAGE_STATUS_QUEUED) {
    try {
      $message->status = CRM_MESSAGE_STATUS_QUEUED;
      $message->revision = TRUE;
      $message->log = format_string('Message (message_id: @message_id) has been queued.', array('@message_id' => $message->message_id));
      entity_save('crm_message', $message);
    }
    catch (Exception $e) {
      // @todo Do something with exceptions!
    }
  }
  elseif (!$message && $message = crm_campaign_channel_create_message($campaign, $channel)) {
    // Message created and queued.
  }
  else {
    watchdog('crm_message', 'Unable to create message for channel_id @channel_id, campaign_id @campaign_id.', array('@channel_id' => $channel->channel_id, '@campaign_id' => $campaign->campaign_id), WATCHDOG_ERROR);
    return FALSE;
  }

  if ($queue_mode) {
    $queue->createItem($message->message_id);
    $context['results']['iterations'][] = array(
      'message_id' => $message->message_id,
      'status' => $message->status,
    );
  }
  else {
    crm_campaign_batch_send_item($message->message_id, $context);
  }

}

/**
 * @param $message_id
 * @param $context
 */
function crm_campaign_batch_send_item($message_id, &$context) {
  crm_message_send_worker_callback_batch_wrapper($message_id, $context);
}

/**
 * @param $success
 * @param $results
 * @param $operations
 */
function crm_campaign_batch_send_finished($success, $results, $operations) {
  if ($success) {
    if (isset($results['iterations'])) {
      $sent = array_filter($results['iterations'], function ($value) {
        return $value['status'] == CRM_MESSAGE_STATUS_SENT;
      });
      $queued = array_filter($results['iterations'], function ($value) {
        return $value['status'] == CRM_MESSAGE_STATUS_QUEUED;
      });
      drupal_set_message(t('@sent messages has been sent. @queued messages has been queued and will be sent later.', array(
        '@sent' => count($sent),
        '@queued' => count($queued),
      )));
    }
    else {
      drupal_set_message(t('Nothing to send'));
    }
    $campaign = entity_load_single('crm_campaign', $results['campaign']);
    if (_crm_campaign_is_sent($campaign->campaign_id)) {
      $campaign->log = 'Campaign has been sent';
      $campaign->revision = TRUE;
      $campaign->status = CRM_CAMPAIGN_STATUS_SENT;
      entity_save('crm_campaign', $campaign);
      drupal_set_message(t('Campaign has been sent'));
    }
  }
  else {
    // An error occurred.
    // $operations contains the operations that remained unprocessed.
    $error_operation = reset($operations);
    drupal_set_message(
      t('An error occurred while processing @operation with arguments: @args',
        array(
          '@operation' => $error_operation[0],
          '@args' => print_r($error_operation[0], TRUE),
        )
      ),
      'error'
    );
  }
}
