<?php

/**
 * @file
 * Implements some hooks to create admin interface for channels.
 */

/**
 * Implements hook_menu().
 */
function crm_channel_ui_menu() {
  $items = array();

  $items['admin/crm/channel/%crm_channel/view'] = array(
    'title' => 'View',
    'page callback' => 'crm_channel_view',
    'page arguments' => array(3),
    'access callback' => 'crm_channel_access',
    'access arguments' => array('view', 3),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'weight' => -2,
  );

  $items['admin/crm/channel/%crm_channel/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'crm_channel_ui_form_wrapper',
    'page arguments' => array(3),
    'access callback' => 'crm_channel_access',
    'access arguments' => array('update', 3),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/crm_channel_ui.form.inc',
    'weight' => -1,
  );

  $items['admin/crm/channel/%crm_channel/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'crm_channel_ui_form_wrapper',
    'page arguments' => array(3, TRUE),
    'access callback' => 'crm_channel_access',
    'access arguments' => array('delete', 3),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/crm_channel_ui.form.inc',
    'weight' => 99,
  );

  $items['admin/crm/channel/add'] = array(
    'title' => 'Add channel',
    'page callback' => 'crm_channel_ui_add',
    'page arguments' => array(),
    'access callback' => 'crm_channel_access',
    'access arguments' => array('create'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/crm_channel_ui.form.inc',
  );

  $items['admin/crm/channel/add/%'] = array(
    'title' => 'Add new channel',
    'page callback' => 'crm_channel_ui_form_wrapper',
    'page arguments' => array(NULL, FALSE, 4),
    'access callback' => 'crm_channel_access',
    'access arguments' => array('create'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/crm_channel_ui.form.inc',
  );

  return $items;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function crm_channel_ui_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'admin/crm/channel' && is_array($data['actions']['output'][0]['#link']['localized_options'])) {
    $data['actions']['output'][0]['#link']['localized_options']['query'] = drupal_get_destination();
  }
}

/**
 * Implements hook_views_api().
 */
function crm_channel_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'crm_channel_ui') . '/includes/views',
  );
}

/**
 * Settings form.
 */
function crm_channel_ui_settings($form, &$form_state, $bundle) {
  return system_settings_form($form);
}

/**
 * Implements hook_entity_info_alter().
 */
function crm_channel_ui_entity_info_alter(&$entity_info) {
  // Expose the admin UI for product fields.
  foreach ($entity_info['crm_channel']['bundles'] as $type => &$bundle) {
    $bundle['admin'] = array(
      'path' => 'admin/crm/config/channel/' . strtr($type, '_', '-'),
      'access arguments' => array('crm manage'),
    );
  }
}
