<?php

/**
 * @file
 * Blocks and logic behind newsletter intetgration.
 */

define('MICRO_CRM_NEWSLETTER_CHANNEL_STATUS', 'newsletter');
define('MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN', 'single_opt_in');
define('MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_DOUBLE_OPT_IN', 'double_opt_in');

/**
 * Implements hook_menu().
 */
function micro_crm_newsletter_menu() {
  $items = array();
  $items['admin/people/micro_crm/config/newsletter'] = array(
    'title' => 'Newsletter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('micro_crm_newsletter_settings'),
    'access arguments' => array('micro crm manage'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'micro_crm_newsletter.admin.inc',
  );
  $items['micro_crm/newsletter'] = array(
    'title' => 'Subscribe',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('micro_crm_newsletter_form'),
    'access arguments' => array('micro crm newsletter subscription'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['micro_crm/newsletter/unsubscribe'] = array(
    'title' => 'Unsubscribe',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('micro_crm_newsletter_unsubscribe_form'),
    'access arguments' => array('micro crm newsletter subscription'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['micro_crm/newsletter/unsubscribe/%micro_crm_channel_token'] = array(
    'page callback' => 'micro_crm_newsletter_unsubscribe_confirmation',
    'page arguments' => array(3),
    'access callback' => 'micro_crm_channel_token_access_callback',
    'access arguments' => array(3),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function micro_crm_newsletter_block_info() {
  return array(
    'newsletter' => array(
      'info' => t('Newsletter'),
      'cache' => DRUPAL_NO_CACHE,
    ),
  );
}

/**
 * Implements hook_permission().
 */
function micro_crm_newsletter_permission() {
  return array(
    'micro crm newsletter subscription' => array(
      'title' => t('Subscribe / unsubscribe newsletter'),
    ),
  );
}

/**
 * Implements hook_micro_crm_channel_status_info().
 */
function micro_crm_newsletter_micro_crm_channel_status_info() {
  $statuses[MICRO_CRM_NEWSLETTER_CHANNEL_STATUS] = array(
    'title' => t('Newsletter'),
    'state' => MICRO_CRM_CHANNEL_STATE_ACTIVE,
  );
  return $statuses;
}

/**
 * Implements hook_block_view().
 */
function micro_crm_newsletter_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'newsletter':
      $block['subject'] = t('Newsletter');
      $block['content'] = drupal_get_form('micro_crm_newsletter_form');
      $block['content']['#attached']['css'][] = drupal_get_path('module', 'micro_crm_newsletter') . '/micro_crm_newsletter.css';
      break;
  }
  return $block;
}

/**
 * Newsletter form.
 */
function micro_crm_newsletter_form($form, &$form_state) {
  $form['#tree'] = TRUE;

  if (!isset($form['#parents'])) {
    $form['#parents'] = array();
  }
  $form['bundles']['#tree'] = TRUE;
  foreach (_micro_crm_newsletter_get_channels() as $channel) {
    $form['bundles'][$channel] = array(
      '#tree' => TRUE,
    );
    $entity = entity_create('micro_crm_channel', array('type' => $channel));
    field_attach_form('micro_crm_channel', $entity, $form['bundles'][$channel], $form_state);
    array_walk_recursive($form['bundles'][$channel], '_micro_crm_reset_required');
  }

  $form['fields'] = array();
  foreach (_micro_crm_newsletter_get_custom_fields() as $field) {
    $instance = field_info_instance('micro_crm_contact', $field, 'micro_crm_contact');
    // Make all custom fields not required.
    $instance['required'] = FALSE;
    $field = field_info_field($field);
    $form['fields'] += field_default_form('micro_crm_contact', NULL, $field, $instance, LANGUAGE_NONE, NULL, $form, $form_state);
  }
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Subscribe'),
  );

  return $form;
}

/**
 * Resets required property so none field is required.
 */
function _micro_crm_reset_required(&$value, $key) {
  if (($key === '#required') && ($value == TRUE)) {
    $value = FALSE;
  }
}

/**
 * @param $form
 * @param $form_state
 */
function micro_crm_newsletter_form_validate(&$form, &$form_state) {
  $empty = 0;
  $channels = _micro_crm_newsletter_get_channels();
  foreach ($channels as $channel) {
    $entity = entity_create('micro_crm_channel', array('type' => $channel));
    field_attach_form_validate('micro_crm_channel', $entity, $form, $form_state);
//    field_attach_submit('micro_crm_channel', $entity, $form, $form_state);
    if (micro_crm_channel_is_empty($channel, $entity)) {
      $empty += 1;
    }
  }
    form_set_error(NULL, t('At least one channel field has to be filled'));
  if ($empty == count(_micro_crm_newsletter_get_channels())) {
  }
}

/**
 * Newsletter form submit callback.
 */
function micro_crm_newsletter_form_submit($form, &$form_state) {
  $channels = array();
  foreach (_micro_crm_newsletter_get_channels() as $channel) {

    // Creates dummy entity.
    $entity = entity_create('micro_crm_channel', array('type' => $channel));

    // Attach all fields to entity.
    field_attach_submit('micro_crm_channel', $entity, $form, $form_state);

    if (micro_crm_channel_is_empty($channel, $entity)) {
      // Skip if channel is empty.
      continue;
    }

    if (!micro_crm_channel_is_unique($channel, $entity)) {
      // Load channel if it already exists.
      $entity = micro_crm_channel_values_load($entity);
      if (!is_object($entity)) {
        watchdog('micro_crm_newsletter', 'Unable to load channel', array(), WATCHDOG_WARNING);
        return;
      }
    }

    // Save channel as a newsletter ready.
    $entity->status = MICRO_CRM_NEWSLETTER_CHANNEL_STATUS;
    $entity->log = 'Channel claimed to receive newsletter messages';
    try {
      entity_save('micro_crm_channel', $entity);
      drupal_set_message(t('!channel has been added to newsletter.', array('!channel' => micro_crm_channel_channel($entity))));
    }
    catch (Exception $e) {
      watchdog_exception('micro_crm_newsletter', $e);
      drupal_set_message(t('!channel: Unable to submit form. Please try again or contact administrator.', array('!channel' => micro_crm_channel_channel($entity))), 'error');
      $form_state['redirect'] = TRUE;
      return;
    }

    // Add to channels array to attach it later to contact.
    $channels[$entity->channel_id] = $entity->channel_id;
  }

  if (count($channels)) {
    // Process entity only if there is something to process.
    $entity = micro_crm_channel_load_contact(array_keys($channels));

    if (is_array($entity) && count($entity) > 1) {
      // If more than one contact found - merge it together.
      $entity = micro_crm_contact_merge($entity);
    }
    elseif (is_array($entity)) {
      // If array contains only one
      $entity = reset($entity);
    }

    // If contact status was in disabled state, bump it to registered.
    $entity->status = MICRO_CRM_CONTACT_STATUS_REGISTERED;

    foreach ($form_state['values']['fields'] as $key => $field) {
      $info = field_info_field($key);
      $entity->{$key} = $field;
      // Check if field is empty and, if so, skip it.
      if (module_invoke($info['module'], 'field_is_empty', $entity->{$key}[LANGUAGE_NONE][0], $info)) {
        unset($entity->{$key});
      }
    }
    $wrapper = entity_metadata_wrapper('micro_crm_contact', $entity);

    $tmp = array();
    foreach ($wrapper->field_micro_crm_channel->getIterator() as $channel) {
      $tmp[] = $channel->getIdentifier();
    }
    foreach ($channels as $channel) {
      if (!in_array($channel, $tmp)) {
        $wrapper->field_micro_crm_channel[] = $channel;
      }
    }

    $entity->log = t('Contact modified by newsletter form.');
    try {
      entity_save('micro_crm_contact', $entity);
    }
    catch (Exception $e) {
      watchdog_exception('micro_crm_newsletter', $e);
      drupal_set_message(t('Unable to submit form. Please try again or contact administrator'), 'error');
      $form_state['redirect'] = TRUE;
      return;
    }
  }
}

/**
 * @param $form
 * @param $form_state
 */
function micro_crm_newsletter_unsubscribe_form($form, &$form_state) {

  $form['#tree'] = TRUE;

  if (!isset($form['#parents'])) {
    $form['#parents'] = array();
  }
  $form['bundles']['#tree'] = TRUE;
  foreach (_micro_crm_newsletter_get_channels() as $channel) {
    $form['bundles'][$channel] = array(
      '#tree' => TRUE,
    );
    $entity = entity_create('micro_crm_channel', array('type' => $channel));
    field_attach_form('micro_crm_channel', $entity, $form['bundles'][$channel], $form_state);
    array_walk_recursive($form['bundles'][$channel], '_micro_crm_reset_required');
  }

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Unsubscribe'),
  );

  return $form;
}

/**
 * @param $form
 * @param $form_state
 */
function micro_crm_newsletter_unsubscribe_form_validate($form, &$form_state) {
  foreach (_micro_crm_newsletter_get_channels() as $channel) {
    $entity = entity_create('micro_crm_channel', array('type' => $channel));
    field_attach_form_validate('micro_crm_channel', $entity, $form, $form_state);
  }
}

/**
 * Unsubscribe form submit callback.
 */
function micro_crm_newsletter_unsubscribe_form_submit($form, &$form_state) {
  foreach (_micro_crm_newsletter_get_channels() as $type) {

    // Creates dummy entity.
    $channel = entity_create('micro_crm_channel', array('type' => $type));

    // Attach all fields to entity.
    field_attach_submit('micro_crm_channel', $channel, $form, $form_state);

    if (micro_crm_channel_is_empty($type, $channel)) {
      // Skip if channel is empty.
      continue;
    }

    if (!($entity = micro_crm_channel_values_load($channel))) {
      // Load channel if it already exists.
      drupal_set_message(t('!channel does not exist in our records.', array('!channel' => micro_crm_channel_channel($channel))), 'warning');
      continue;
    }
    $channel = $entity;
    $channel->unsubscribe = TRUE;
    try {
      entity_save('micro_crm_channel', $channel);
    }
    catch (Exception $e) {
      watchdog_exception('micro_crm_newsletter', $e);
      drupal_set_message(t('!channel: Unable to submit form. Please try again or contact administrator', array('!channel' => micro_crm_channel_channel($channel))), 'error');
      $form_state['redirect'] = TRUE;
      return;
    }
  }
}

/**
 * @param $channel
 */
function micro_crm_newsletter_unsubscribe_confirmation($channel) {
  try {
    $channel->status = MICRO_CRM_CHANNEL_STATUS_REGISTERED;
    $channel->log = 'Channel does not want to receive newsletter messages';
    entity_save('micro_crm_channel', $channel);
    drupal_set_message(t('!channel: Subscription has been canceled.', array('!channel' => micro_crm_channel_channel($channel))));
    drupal_goto('<front>');
  }
  catch (Exception $e) {
    watchdog_exception('micro_crm_newsletter', $e);
    drupal_set_message(t('!channel: Unable to change subscription status', array('!channel' => micro_crm_channel_channel($channel))), 'error');
  }
}

/**
 * Implements hook_micro_crm_channel_presave().
 */
function micro_crm_newsletter_micro_crm_channel_presave($channel) {
  if (isset($channel->unsubscribe) && $channel->unsubscribe == TRUE) {
    $method = variable_get('micro_crm_channel_ui_' . $channel->type . '_newsletter', MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN);
    if ($method == MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN) {
      // Disable newsletter status for channel..
      $channel->status = MICRO_CRM_CHANNEL_STATUS_REGISTERED;
      $channel->log = 'Channel does not want to receive newsletter messages';
    }
    elseif ($method == MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_DOUBLE_OPT_IN) {
      _micro_crm_channel_generate_token($channel);
      $channel->log = 'Channel token has been generated';
    }
  }
}

/**
 * Implements hook_micro_crm_channel_update().
 */
function micro_crm_newsletter_micro_crm_channel_update($channel) {
  if (isset($channel->unsubscribe) && $channel->unsubscribe == TRUE) {
    $method = variable_get('micro_crm_channel_ui_' . $channel->type . '_newsletter', MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN);
    if ($method == MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN) {
      drupal_set_message(t('You will not receive newsletter messages any more.'));
    }
    elseif ($method == MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_DOUBLE_OPT_IN) {
      // @todo: send message here
      drupal_set_message(t('!channel: Message has been sent. Click on the confirmation link to complete.', array('!channel' => micro_crm_channel_channel($channel))), 'warning');
    }
  }
}

/**
 * @return array
 *   Array of channels in key => key format.
 */
function _micro_crm_newsletter_get_channels() {
  $channels = array();
  foreach (variable_get('micro_crm_newsletter_channels', array()) as $channel) {
    if ($channel === 0) {
      continue;
    }
    $channels[$channel] = $channel;
  }
  return $channels;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function micro_crm_newsletter_form_micro_crm_channel_ui_settings_alter(&$form, &$form_state) {
  if (isset($form_state['build_info']['args'][0]) && $type = $form_state['build_info']['args'][0]);
  $form['micro_crm_channel_ui_' . $type . '_newsletter'] = array(
    '#type' => 'radios',
    '#title' => t('Unsubscribe'),
    '#default_value' => variable_get('micro_crm_channel_ui_' . $type . '_newsletter', MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN),
    '#options' => array(
      MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_SINGLE_OPT_IN => t('Single opt in'),
      MICRO_CRM_NEWSLETTER_UNSUBSCRIBE_DOUBLE_OPT_IN => t('Double opt in'),
    ),
  );
}

/**
 * @return array
 *   Array of channels in key => key format.
 */
function _micro_crm_newsletter_get_custom_fields() {
  $custom_fields = array();
  foreach (variable_get('micro_crm_newsletter_custom_fields', array()) as $custom_field) {
    if ($custom_field === 0) {
      continue;
    }
    $custom_fields[$custom_field] = $custom_field;
  }
  return $custom_fields;
}
